Update patch set 1
Patch Set 1:

Build Failed 

https://jenkins.onap.org/job/integration-xtesting-security-docker-merge-istanbul/82/ : FAILURE

Syntax error in markdown file ( https://jenkins.onap.org/job/integration-xtesting-security-docker-merge-istanbul/82/ )

Logs: https://logs.onap.org/production/vex-yul-ecomp-jenkins-1/integration-xtesting-security-docker-merge-istanbul/82

https://jenkins.onap.org/job/integration-xtesting-healthcheck-docker-merge-istanbul/81/ : FAILURE

No problems were identified. If you know why this problem occurred, please add a suitable Cause for it. ( https://jenkins.onap.org/job/integration-xtesting-healthcheck-docker-merge-istanbul/81/ )

Logs: https://logs.onap.org/production/vex-yul-ecomp-jenkins-1/integration-xtesting-healthcheck-docker-merge-istanbul/81

https://jenkins.onap.org/job/integration-xtesting-infra-healthcheck-docker-merge-istanbul/80/ : FAILURE

Syntax error in markdown file ( https://jenkins.onap.org/job/integration-xtesting-infra-healthcheck-docker-merge-istanbul/80/ )

There are broken links in the documentation
https://git.onap.org/integration/xtesting.git to commit f0b34e8a3b3a6f2cc55dbcb7c4f3e16f55bb7dbd
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status "error"
[91m  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c "import io, os, sys, setuptools, tokenize; sys.argv[0] = """""/tmp/pip-req-build-c_v606bv/infra-healthcheck/setup.py"""""; __file__="""""/tmp/pip-req-build-c_v606bv/infra-healthcheck/setup.py""""";f = getattr(tokenize, """""open""""", open)(__file__) if os.path.exists(__file__) else io.StringIO("""""from setuptools import setup; setup()""""");code = f.read().replace("""""\r\n""""", """""\n""""");f.close();exec(compile(code, __file__, """""exec"""""))" egg_info --egg-base /tmp/pip-pip-egg-info-ycbtj5oj
       cwd: /tmp/pip-req-build-c_v606bv/infra-healthcheck
  Complete output (20 lines):
  ERROR:root:Error parsing
  Traceback (most recent call last):
    File "/usr/lib/python3.8/site-packages/pbr/core.py", line 96, in pbr
      attrs = util.cfg_to_args(path, dist.script_args)
    File "/usr/lib/python3.8/site-packages/pbr/util.py", line 271, in cfg_to_args
      pbr.hooks.setup_hook(config)
    File "/usr/lib/python3.8/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
      metadata_config.run()
    File "/usr/lib/python3.8/site-packages/pbr/hooks/base.py", line 27, in run
      self.hook()
    File "/usr/lib/python3.8/site-packages/pbr/hooks/metadata.py", line 25, in hook
      self.config["version"] = packaging.get_version(
    File "/usr/lib/python3.8/site-packages/pbr/packaging.py", line 865, in get_version
      version = _get_version_from_git(pre_version)
    File "/usr/lib/python3.8/site-packages/pbr/packaging.py", line 805, in _get_version_from_git
      result = _get_version_from_git_target(git_dir, target_version)
    File "/usr/lib/python3.8/site-packages/pbr/packaging.py", line 764, in _get_version_from_git_target
      raise ValueError(
  ValueError: git history requires a target version of pbr.version.SemanticVersion(1.9.1), but target version is pbr.version.SemanticVersion(1.0.0)
  error in setup command: Error parsing /tmp/pip-req-build-c_v606bv/infra-healthcheck/setup.cfg: ValueError: git history requires a target version of pbr.version.SemanticVersion(1.9.1), but target version is link mentioned in line 1 are not answering ( https://jenkins.onap.org/job/integration-xtesting-infra-healthcheck-docker-merge-istanbul/80/ )

Logs: https://logs.onap.org/production/vex-yul-ecomp-jenkins-1/integration-xtesting-infra-healthcheck-docker-merge-istanbul/80

https://jenkins.onap.org/job/integration-xtesting-smoke-usecases-robot-docker-merge-istanbul/81/ : FAILURE

No problems were identified. If you know why this problem occurred, please add a suitable Cause for it. ( https://jenkins.onap.org/job/integration-xtesting-smoke-usecases-robot-docker-merge-istanbul/81/ )

Logs: https://logs.onap.org/production/vex-yul-ecomp-jenkins-1/integration-xtesting-smoke-usecases-robot-docker-merge-istanbul/81

https://jenkins.onap.org/job/integration-xtesting-smoke-usecases-robot-py3-docker-merge-istanbul/81/ : SUCCESS

Logs: https://logs.onap.org/production/vex-yul-ecomp-jenkins-1/integration-xtesting-smoke-usecases-robot-py3-docker-merge-istanbul/81

https://jenkins.onap.org/job/integration-xtesting-smoke-usecases-pythonsdk-docker-merge-istanbul/80/ : SUCCESS

Logs: https://logs.onap.org/production/vex-yul-ecomp-jenkins-1/integration-xtesting-smoke-usecases-pythonsdk-docker-merge-istanbul/80

Patch-set: 1