Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://jenkins.onap.org/job/integration-xtesting-master-commit-lint/263/ : FAILURE

The Commit title must follow this pattern "[WHAT] A title"

WHAT can be a component name (AAI for example), DOC for documentation, COMMON for common, ...

The title must start with a capital letter (A in the example) and a space must be set between the end of the topic and the actual title: "] A title" ( https://jenkins.onap.org/job/integration-xtesting-master-commit-lint/263/ )

The line in commit is too long: it has a size of 130 instead of 80 characters maximum.

Line in cause: ImportError: cannot import name "DEFAULT_CIPHERS" from "urllib3.util.ssl_" (/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py) ( https://jenkins.onap.org/job/integration-xtesting-master-commit-lint/263/ )

Logs: https://logs.onap.org/production/vex-yul-ecomp-jenkins-1/integration-xtesting-master-commit-lint/263

https://jenkins.onap.org/job/integration-xtesting-healthcheck-docker-verify-master/349/ : SUCCESS

Logs: https://logs.onap.org/production/vex-yul-ecomp-jenkins-1/integration-xtesting-healthcheck-docker-verify-master/349

https://jenkins.onap.org/job/integration-xtesting-security-docker-verify-master/357/ : SUCCESS

Logs: https://logs.onap.org/production/vex-yul-ecomp-jenkins-1/integration-xtesting-security-docker-verify-master/357

https://jenkins.onap.org/job/integration-xtesting-smoke-usecases-robot-docker-verify-master/349/ : SUCCESS

Logs: https://logs.onap.org/production/vex-yul-ecomp-jenkins-1/integration-xtesting-smoke-usecases-robot-docker-verify-master/349

https://jenkins.onap.org/job/integration-xtesting-smoke-usecases-pythonsdk-docker-verify-master/353/ : SUCCESS

Logs: https://logs.onap.org/production/vex-yul-ecomp-jenkins-1/integration-xtesting-smoke-usecases-pythonsdk-docker-verify-master/353

https://jenkins.onap.org/job/integration-xtesting-infra-healthcheck-docker-verify-master/355/ : SUCCESS

Logs: https://logs.onap.org/production/vex-yul-ecomp-jenkins-1/integration-xtesting-infra-healthcheck-docker-verify-master/355

https://jenkins.onap.org/job/integration-xtesting-smoke-usecases-robot-py3-docker-verify-master/170/ : SUCCESS

Logs: https://logs.onap.org/production/vex-yul-ecomp-jenkins-1/integration-xtesting-smoke-usecases-robot-py3-docker-verify-master/170

Patch-set: 1
Reviewer: Gerrit User 459 <459@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=-1, 8f48dc5a0681e500dabd7865732c57239e41f631
Attention: {"person_ident":"Gerrit User 2679 \u003c2679@14b4e41f-c4e3-4fb9-9955-6a9b5656895a\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}